import { INTEREST_LEVEL, STATUS, SOURCE } from "../types/global";

const LEAD_SOURCE = [
  SOURCE.REFERRAL,
  SOURCE.WEBSITE,
  SOURCE.COLD_CALL,
  SOURCE.EVENT,
];

const LEAD_INTEREST_LEVEL = [
  INTEREST_LEVEL.LOW,
  INTEREST_LEVEL.MEDIUM,
  INTEREST_LEVEL.HIGH,
];

const LEAD_STATUS = [
  STATUS.NEW,
  STATUS.CLOSED,
  STATUS.QUALIFIED,
  STATUS.CONTACTED,
];

export { LEAD_SOURCE, LEAD_INTEREST_LEVEL, LEAD_STATUS };
